version: "3.8"

networks: 
    bd_network:
    api_network:

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: "bd"
        ports:
            - "1433:1433"
        networks: 
            - bd_network
        environment:             
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrong(!)Password
    apirest:
        container_name: "apirest"
        build:
            context: ./PotentialCrudAPI/
            dockerfile: Dockerfile
        ports:
            - "6651:80"
        depends_on: 
            - sqlserver
        networks: 
            - bd_network
        links: 
            - "sqlserver:bdcontainer"
    front:
        container_name: "front"
        build:
            context: ./FrontEnd/potential_crud_front/
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on: 
            - apirest
        networks: 
            - api_network
    

  